### PR TITLE
Support partially covered lines

### PR DESCRIPTION
**Pull request by loganek**

### CODE REVIEW

**Comment by danielpalme** [comment]
Good idea.
Your code works fine for DynamicCodeCoverageParser, but not for the other parsers.
I will try to come up with a solution for all parsers within the next days.

**Comment by loganek** [comment]
Why do you mean that it doesn't work with the other parsers? If the file doesn't contain "partially", it'll automatically set the line state as "covered", so it should work as before my changes.

**Comment by danielpalme** [comment]
The array containing the lineVisits contains the number of visits per line.
That means 2 = 2 visits, 3 = 3 visits... -1 = not coverable.
DynamicCodeCoverage does not count the number of visits. It just contains Yes/No/Partial.
But others coverage tools count the visits per line.

Now you are using 1 = partial, 2 = full. That works well for DynamicCodeCoverage but not for the other ones.

But your idea is good and I will make sure it works with the other parsers as well.

**Comment by loganek** [comment]
Thanks for explanation. Unfortunately, I wasn't aware of the other parsers, and I don't even have environment configured to do tests for the other providers, so that would be cool if you could do some more testing :) Thanks

**Comment by danielpalme** [comment]
I updated your solution in commit [de2e51a](https://github.com/danielpalme/ReportGenerator/commit/de2e51abbe013b05a136d7d8d6a67b00506ea447).
Now all parsers are fully supported.

This beta contains the changes:
https://www.nuget.org/packages/ReportGenerator/2.5.0-beta1

**Comment by loganek** [comment]
Thanks a lot

**Pull request merged**
