### PR TITLE
Update custom-azurepipelines.css

### PR DESCRIPTION
**Pull request by knom**
Somehow the HTML font-family wasn't rendered in the resulting output HTML..

Trying it in BODY now..

Sorry for the duplicate effort!
Could you maybe try out locally whether the HTML is as expected before publishing to VSTS marketplace?

### CODE REVIEW

**Comment by danielpalme** [comment]
Locally you changes don't make any difference. Did you verify the changes by applying them in sample report in Azure DevOps (just hit F12 in your browser and add the rules to the body element)?

**Comment by knom** [comment]
Yes.. But locally even originally on the HTML element they made sense..

Then in VSTS the report was rendered so that the style was "magically" gone from the HTML..
(really physically NOT present in the rendered HTML)

Weird..

**Comment by danielpalme** [comment]
Just updated the marketplace version.
Could you please try it and let me know if this works for you?

**Comment by danielpalme** [comment]
Moving the CSS rule to the body doesn't help. I'm closing this PR. Let's continue the discussion in #176

**Pull request closed without merging**
