### PR TITLE
Make Cobertura line-rate and branch-rate optional for methods

### PR DESCRIPTION
**Pull request by david-driscoll**
This is a fix so that the report generator can be used with https://github.com/istanbuljs/nyc which currently doesn't add metrics for lines / branches on a method.

I'm not sure what additional things you need for a pull request I can supply an example cobertura file if that will help!

### CODE REVIEW

**Comment by danielpalme** [comment]
The code looks fine. An example cobertura file would be perfect.

**Comment by david-driscoll** [comment]
Sample file added, let me know if the folder placement is alright.  I also didn't know how or where it would be wired into integration testing.  If there is a good place for that I can do that as well.

**Comment by danielpalme** [comment]
New release is available:
https://www.nuget.org/packages/ReportGenerator/2.5.7

**Comment by david-driscoll** [comment]
That was blazing fast... thanks so much!!

**Pull request merged**
