### PR TITLE
Risk hotspots

### PR DESCRIPTION
**Pull request by kurattila**
Hello,
please consider this feature of showing the *riskiest methods* in the summary.

A "word cloud", weighted by the CRAP score metrics.
Most CRAPPY methods")

### CODE REVIEW

**Comment by danielpalme** [comment]
Nice idea and thanks for your PR.
I will have a detailed look at it soon.

I have to make sure your code works for all possible input files and also older versions of OpenCover which don't have the crap score.
I'm also thinking about moving those hotspots to a separate page and maybe add some other hotspots based on other metrics.

**Comment by kurattila** [comment]
Thanks for the hint; I've added a fix for having Risk Hotspots rendered only if CRAP score is available.

**Comment by danielpalme** [comment]
I probably will integrate this in the next release.
But it may take some time, since I'm working at some other projects right now.

**Comment by danielpalme** [comment]
I integrated your PR, but applied some changes.
- I replaced the cloud with a table
- I made the metrics handling more generic with customizable thresholds for the relevant metrics

This is the current state of the table:
hotspots

You can have a look at this beta:
https://www.nuget.org/packages/ReportGenerator/3.1.0-beta1

The report currently shows the TOP 20 hotspots.
I will add some filter/sorting options before finally releasing this new feature.

**Comment by kurattila** [comment]
Thanks for merging!

**Pull request merged**
